services:
###> doctrine/doctrine-bundle ###
  database:
    image: mariadb:11.4
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE:-pedagoflow}
      MARIADB_USER: ${MARIADB_USER:-pedagoflow}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-pedagoflow}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-rootpwd}
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - database_data:/var/lib/mysql:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
